server:
  port: 8080
  host: http://localhost:8080
aws:
  bucket: amacoondocs
smtp:
  host: smtp.kinghost.net
  port: 587
  username: sistema@catclubsystem.com
  password: Sistema@0013
  systemEmail: sistema@catclubsystem.com
  adminEmail: scuba13@hotmail.com
