db:
  username: catclubsystem
  password: 2010amacoon2010
  host: dbcatclubsystem.c1o2yissukzs.sa-east-1.rds.amazonaws.com
  port: 5432
  name: dbcatclubsystem

server:
  port: 8080
  host: http://localhost:8080
aws:
  S3AwsAccessKeyId: AKIAVRUVP7BCRAJZLKOT
  S3AwsSecretAccessKey: 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
  bucket: amacoondocs
smtp:
  host: smtp.kinghost.net
  port: 587
  username: sistema@catclubsystem.com
  password: Sistema@0013
  systemEmail: sistema@catclubsystem.com
  adminEmail: scuba13@hotmail.com
jwt:
  secret: RagnarPi