db:
  username: catclubsystem
  password: teste
  host: localhost
  port: 5432
  name: dbcatclubsystem

server:
  port: 8080
  host: http://localhost:8080
aws:
  S3AwsAccessKeyId: AKIA4R4F43U6FT2QGREN
  S3AwsSecretAccessKey: 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
  bucket: amacoondocs
smtp:
  host: smtp.kinghost.net
  port: 587
  username: sistema@catclubsystem.com
  password: Sistema@0013
  systemEmail: sistema@catclubsystem.com
  adminEmail: scuba13@hotmail.com
jwt:
  secret: RagnarPi