server:
  port: 8080
  host: https://amacoon.fq8n18ftegddi.us-east-1.cs.amazonlightsail.com
aws:
  bucket: amacoondocs
smtp:
  host: smtp.kinghost.net
  port: 587
  username: sistema@catclubsystem.com
  password: Sistema@0013
  systemEmail: sistema@catclubsystem.com
  adminEmail: scuba13@hotmail.com

