version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dbcatclubsystem
      POSTGRES_USER: catclubsystem
      POSTGRES_PASSWORD: 2010mainecoon2010
    ports:
      - "5432:5432"
    volumes:
      - postgress:/var/lib/postgresql/data

volumes:
  postgress:
