apiVersion: apps/v1
kind: Deployment
metadata:
  name: amacconservice
  namespace: catclubsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amacconservice
  template:
    metadata:
      labels:
        app: amacconservice
    spec:
      serviceAccountName: amacoonservicesccount
      containers:
      - name: amacconservice
        image: IMAGE_URL_PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
