apiVersion: apps/v1
kind: Deployment
metadata:
  name: amacconservice
  namespace: catclubsystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amacconservice
  template:
    metadata:
      labels:
        app: amacconservice
    spec:
      serviceAccountName: amacoonservicesccount
      containers:
      - name: amacconservice
        image: 381491869765.dkr.ecr.sa-east-1.amazonaws.com/catclubsystem:amacconservice-21e03d7
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
