apiVersion: apps/v1
kind: Deployment
metadata:
  name: amacconservice
  namespace: catclubsystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amacconservice
  template:
    metadata:
      labels:
        app: amacconservice
    spec:
      serviceAccountName: amacoonservicesccount  # Nome do Service Account
      containers:
      - name: amacconservice
        image: 381491869765.dkr.ecr.sa-east-1.amazonaws.com/catclubsystem:latest
        
        ports:
        - containerPort: 8080
