apiVersion: v1
kind: Service
metadata:
  name: amacconservice
  namespace: catclubsystem
spec:
  selector:
    app: amacconservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer