name: Docker Build and Push and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
            
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Set environment variables
        id: vars
        run: |
          echo "::set-output name=ecr_registry::${{ steps.login-ecr.outputs.registry }}"
          echo "::set-output name=image_repo::amacconservice"
          echo "::set-output name=image_tag::latest"
      
      - name: Build and tag Docker image
        run: docker build -t ${{ steps.vars.outputs.ecr_registry }}/${{ steps.vars.outputs.image_repo }}:${{ steps.vars.outputs.image_tag }} .
              
      - name: Push Docker image to ECR
        run: docker push ${{ steps.vars.outputs.ecr_registry }}/${{ steps.vars.outputs.image_repo }}:${{ steps.vars.outputs.image_tag }}
      
      # Adicione os passos abaixo

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: aws eks --region sa-east-1 update-kubeconfig --name EKS_Edu
      
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
