name: Deploy to Linux

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
      - name: Build app for Linux
        run: go build -o amacoonServices cmd/server/main.go 
      - name: Upload binary to Linux via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.1
        with:
          server: ftp.catclubsystem.com
          username: catclubsystem
          password: 2010mainecoon2010
          local-dir: ./
          remote-dir: /home/catclubsystem/amacoonservice
      - name: Execute app on Linux via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ftp.catclubsystem.com
          username: catclubsystem
          password: 2010mainecoon2010
          port: 22
          script: |
            cd /home/catclubsystem/amacoonservice
            ./amacoonServices
